### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by myfreeer** [myfreeer/GreenChrome#2]
- [x] 允许并非来自 Chrome 网上应用店的扩展
- [x] 去除启动时禁用以开发者模式加载的扩展提示
- [ ] 允许自动设置为默认
- [ ] 内置插入策略功能

20160627增加
- [ ] 实现基于C的Registry.pol编辑
- [ ] 重定向Registry.pol到User Data，实现便携化
- [ ] 右键快捷菜单增加/修改/删除
- [ ] 快捷键修改/禁用

**Comment by myfreeer** [comment]
关键文件：C:\Windows\System32\GroupPolicy\Machine\Registry.pol
refs:
https://github.com/dlwyatt/PolicyFileEditor/blob/master/Commands.ps1
https://github.com/finarfin/GroupPolicy.Parser
https://technet.microsoft.com/en-us/library/ee461027.aspx
https://gallery.technet.microsoft.com/scriptcenter/Read-or-modify-Registrypol-778fed6e
https://gallery.technet.microsoft.com/scriptcenter/Read-or-modify-Registrypol-447677e7
http://stackoverflow.com/questions/3137215/how-to-modify-local-group-policy-setting-programatically
http://pete.akeo.ie/2011/03/porgramatically-setting-and-applying.html
https://msdn.microsoft.com/en-us/library/aa374235.aspx
https://blogs.technet.microsoft.com/fdcc/2008/05/07/utilities-for-automating-local-group-policy-management/
https://bitbucket.org/MartinEden/local-policy
http://www.lshift.net/blog/2013/03/25/programmatically-updating-local-policy-in-windows/
https://gallery.technet.microsoft.com/scriptcenter/Read-or-modify-Registrypol-447677e7
https://www.autoitscript.com/forum/topic/141076-registry-policy-file-editor/

**Comment by myfreeer** [comment]
批处理实现：
https://github.com/myfreeer/enableallExtensions

**Comment by myfreeer** [comment]
*去除启动时禁用以开发者模式加载的扩展提示的批处理(Powershell)实现：
https://gist.github.com/myfreeer/3db8a9cd3a92f37aa7b00208eea8f57e

orig [here](http://stackoverflow.com/questions/30287907/how-to-hack-chrome-dll-to-get-rid-of-the-disable-developer-mode-extensions-pop/30361260#30361260)

特征码（x64）：
(Binary) FE83F8**03**7D??833D -> FE83F8**09**7D??833D
(ASCII) ExtensionDeveloperModeWarning (457874656E73696F6E446576656C6F7065724D6F64655761726E696E67) -> (Anything else)
